# Generated by Django 5.1.1 on 2024-09-29 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_scoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubmission',
            name='resume',
            field=models.CharField(max_length=8000),
        ),
    ]
