# Generated by Django 5.1.1 on 2024-09-29 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_scoring', '0002_alter_usersubmission_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmission',
            name='service',
            field=models.CharField(default='llama', max_length=20),
            preserve_default=False,
        ),
    ]
