# Generated by Django 5.1.1 on 2024-09-30 00:54

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_scoring', '0003_usersubmission_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubmission',
            name='id',
            field=models.UUIDField(default=uuid6.uuid6, editable=False, primary_key=True, serialize=False),
        ),
    ]
