# Generated by Django 3.2.23 on 2024-09-30 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_scoring', '0004_alter_usersubmission_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmission',
            name='company',
            field=models.CharField(default='Dover', max_length=200),
            preserve_default=False,
        ),
    ]
